# Generated by Django 5.1.1 on 2024-10-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_rename_user_skill_student_remove_skill_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(default='Без категории', max_length=30),
        ),
    ]
